/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf --transform 
Files: scene.gltf [13.84MB] > scene-transformed.glb [1.58MB] (89%)
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera makeDefault={false} far={100} near={0.1} fov={22.895} position={[6.536, 1.586, 6.926]} rotation={[-0.257, 0.791, 0.187]} />
      <mesh geometry={nodes.Plane.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Plane_1.geometry} material={materials.PaletteMaterial002} />
      <mesh geometry={nodes.Plane_3.geometry} material={materials.PaletteMaterial003} />
      <mesh geometry={nodes.Back_LeftDoorHandle.geometry} material={materials.PaletteMaterial004} position={[0.884, 0.407, -1.19]} />
      <mesh geometry={nodes.BackWindow.geometry} material={materials.PaletteMaterial005} />
      <mesh geometry={nodes.Plane003_2.geometry} material={materials.PaletteMaterial006} position={[-0.002, 0.618, -1.902]} />
      <mesh geometry={nodes.BMW_Interior.geometry} material={materials.PaletteMaterial007} />
      <mesh geometry={nodes.Seats.geometry} material={materials.Leather} />
      <mesh geometry={nodes.Cylinder_2.geometry} material={materials.PaletteMaterial008} scale={0.095} />
      <mesh geometry={nodes.Cylinder_3.geometry} material={materials.PaletteMaterial008} scale={0.095} />
      <mesh geometry={nodes.Cylinder_4.geometry} material={materials.PaletteMaterial009} scale={0.095} />
      <mesh geometry={nodes.Front_RightTyre.geometry} material={materials.Tyre} position={[-0.875, -0.188, 1.65]} scale={[0.986, 1, 1]} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
