/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Tablet.gltf --transform 
Files: Tablet.gltf [1.59MB] > Tablet-transformed.glb [132.33KB] (92%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Tablet-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube_1.geometry} material={materials.Tablet} />
      <mesh geometry={nodes.Cube_2.geometry} material={materials.Screen} />
      <mesh geometry={nodes.Cube_3.geometry} material={materials.Logo} />
      <mesh geometry={nodes.Cube_4.geometry} material={materials.Button} />
    </group>
  )
}

useGLTF.preload('/Tablet-transformed.glb')
